apiVersion: v1
kind: Secret
metadata:
  name: sftptos3-secret
  namespace: prod
type: Opaque
stringData:
  db.username: "root"
  db.password: "111"

#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
